### ISSUE TITLE
Issues running npm scripts in docker

### ISSUE THREAD

**Issue by lukenewman** [aave/lens-protocol#14]
Following the steps in the [docs](https://docs.lens.dev/docs/deploying-the-protocol), I'm unable to get `npm run compile`  to run successfully. First, I had to `npm install` (which should prob be added to the docs -- the compose command doesn't seem to be doing the trick?) when getting `hardhat not found`, but now I'm getting this after an npm install:

```
node@8609d1131323:/src$ npm run compile

> lens-protocol@1.0.0 compile
> SKIP_LOAD=true hardhat clean && SKIP_LOAD=true hardhat compile

Error: ENOENT: no such file or directory, open '/src/node_modules/@solidity-parser/parser/dist/antlr/Solidity.tokens'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at /src/node_modules/@solidity-parser/parser/src/tokens-string.js:8:6
    at /src/node_modules/@solidity-parser/parser/dist/index.cjs.js:22:45
    at Object.<anonymous> (/src/node_modules/@solidity-parser/parser/src/tokens.ts:2:27)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

`@solidity-parser/parser` isn't in the `package.json`. Should it be? Adding it and running `npm run compile` again gives me this:

```
node@8609d1131323:/src$ npm run compile

> lens-protocol@1.0.0 compile
> SKIP_LOAD=true hardhat clean && SKIP_LOAD=true hardhat compile

An unexpected error occurred:

TypeError: envPaths is not a function
    at generatePathsSync (/src/node_modules/hardhat/src/internal/util/global-dir.ts:16:10)
    at getConfigDirSync (/src/node_modules/hardhat/src/internal/util/global-dir.ts:20:22)
    at Object.hasConsentedTelemetry (/src/node_modules/hardhat/src/internal/util/global-dir.ts:103:21)
    at main (/src/node_modules/hardhat/src/internal/cli/cli.ts:136:49)
```

Is this the best place to raise issues about the docs?

**Comment by Kosta7** [comment]
Having a similar issue here:

```
node@79d6454a2399:/src$ npm run compile

> lens-protocol@1.0.0 compile
> SKIP_LOAD=true hardhat clean && SKIP_LOAD=true hardhat compile

Error: Cannot find module '/src/node_modules/fs-extra/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/src/node_modules/hardhat/src/internal/core/params/argumentTypes.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
node@79d6454a2399:/src$
```

**Comment by codlapse** [comment]
delete the module and install the dependencies again. It works for me
1.rm -rf node_modules package-lock.json
2.npm install

**Comment by qwolphin** [comment]
Closing, feel free to reopen is there are any problems with the latest config
