### ISSUE TITLE
[Solved] Testing follow module is error 

### ISSUE THREAD

**Issue by LI-YONG-QI** [aave/lens-protocol#146]
Hi all!
I followed the [docs](https://docs.lens.xyz/docs/testing-a-module) to test follow module
Task and module contract are copied from the document
But I got this error when I run task

```An unexpected error occurred:

Error: call revert exception (method="getFollowNFT(uint256)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at Logger.makeError (/Users/li/lens-protocol/node_modules/@ethersproject/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/Users/li/lens-protocol/node_modules/@ethersproject/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at Interface.decodeFunctionResult (/Users/li/lens-protocol/node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/src.ts/interface.ts:425:23)
    at Contract.<anonymous> (/Users/li/lens-protocol/node_modules/@ethersproject/contracts/src.ts/index.ts:392:44)
    at step (/Users/li/lens-protocol/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/li/lens-protocol/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/li/lens-protocol/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getFollowNFT(uint256)',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x1A1FEe7EeD918BD762173e4dc5EfDB8a78C924A8',
  args: [ 1 ],
  transaction: {
    data: '0xa9ec65630000000000000000000000000000000000000000000000000000000000000001',
    to: '0x1A1FEe7EeD918BD762173e4dc5EfDB8a78C924A8',
    from: '0xeAD9C93b79Ae7C1591b1FB5323BD777E86e150d4'
  }
}
```

Can anyone help me?

**Comment by LI-YONG-QI** [comment]
I solved this issue after run task of full-deploy on localhost
